### ISSUE TITLE
We need a diffrent design for showing our team

### ISSUE THREAD

**Issue by aminenurgynk** [octoposprime/op-fe-web#50]
![4](https://github.com/octoposprime/op-web-site/assets/130973404/de869be4-47a8-47f8-8ce2-4203a6ca2380)
![5](https://github.com/octoposprime/op-web-site/assets/130973404/6ee33acb-a897-4f56-9f87-a1eab2b03c8b)
![6](https://github.com/octoposprime/op-web-site/assets/130973404/004915e9-95ac-4027-ac29-a5d905623329)

Description:
We just need a good design, one page is enough, here is your examples.

Loom Link:
https://www.loom.com/share/43ded882eac047ddbb4df416ef7075bf

Figma Link:
https://www.figma.com/design/hnvVfV2xzpcPW1ZkybkDxe/OctopOSPrime-web-site?node-id=105%3A38&t=XO1kkfrlpsucLaFq-1

**Comment by sudenznl** [comment]
![_d3916ef2-710d-4db9-a00d-deab7c80f2d2](https://github.com/octoposprime/op-web-site/assets/118690915/d538d849-faba-4131-9849-d3b50178c241)
![_0377f8bc-62f4-429e-91db-026501227477](https://github.com/octoposprime/op-web-site/assets/118690915/ea85464d-c6ac-470c-87cc-c0c69cbe3a9e)

**Comment by sudenznl** [comment]
Attached are the designs I created
[Uploading issue.zip…]()

**Comment by sudenznl** [comment]
designs I have created: 

![_38bdbb18-58c2-4830-bf44-eef621d036f7](https://github.com/octoposprime/op-web-site/assets/118690915/9909efb6-69aa-4cfc-b15f-bb6bc4096c34)
![_47bf61d5-91fc-4557-b3d2-921514357527](https://github.com/octoposprime/op-web-site/assets/118690915/bbb04e1e-08c5-4dd5-a011-037d4f11b18b)
![_68ca13a0-d7ff-4214-b771-9cb4f605f608](https://github.com/octoposprime/op-web-site/assets/118690915/6d123499-6b06-42a1-9f55-8b97f55f5a77)
![_0377f8bc-62f4-429e-91db-026501227477](https://github.com/octoposprime/op-web-site/assets/118690915/e4c9bf31-b284-4eea-b2a7-f49388fafde6)
![_a069b08a-1a14-469c-bf0f-5dcf718cb3d7](https://github.com/octoposprime/op-web-site/assets/118690915/05a8bf85-5617-4cc7-9adb-18d815175a1e)
![_c7fd88d1-bed3-4776-8cdc-136775916b6a](https://github.com/octoposprime/op-web-site/assets/118690915/72590692-b38e-4c84-a97a-de418fd5826f)
![_d3916ef2-710d-4db9-a00d-deab7c80f2d2](https://github.com/octoposprime/op-web-site/assets/118690915/a3ee8be5-48ca-463f-bb3d-a1b675dac831)

**Comment by aminenurgynk** [comment]
Thanks :)
